export const POUCH_DB = [
  { b: "77 Pouches", n: "77 Black Currant Ice", mg: 10.4 },
  { b: "77 Pouches", n: "77 Blueberry", mg: 10.4 },
  { b: "77 Pouches", n: "77 Cola & Cherry", mg: 10.4 },
  { b: "77 Pouches", n: "77 Cola & Vanilla", mg: 10.4 },
  { b: "77 Pouches", n: "77 Forest Fruit Light", mg: 5.2 },
  { b: "ACE", n: "Ace Cool Mint", mg: 6.0 },
  { b: "ACE", n: "Ace Eucalyptus", mg: 6.0 },
  { b: "ACE", n: "Ace Extreme Cool", mg: 11.2 },
  { b: "ACE", n: "Ace Green Lemon", mg: 6.0 },
  { b: "ACE", n: "Ace X EXTEND Cool Mint", mg: 10.0 },
  { b: "AROMA KING", n: "Aroma King Full Kick Candy Tobacco", mg: 10.0 },
  { b: "AROMA KING", n: "Aroma King Full Kick Double Mint", mg: 10.0 },
  { b: "AROMA KING", n: "Aroma King Soft Kick Candy Tobacco", mg: 5.0 },
  { b: "AROMA KING", n: "Aroma King Soft Kick Double Mint", mg: 5.0 },
  { b: "CLEW", n: "Clew Mango Mint", mg: 10.0 },
  { b: "CLEW", n: "Clew Watermelon Ice", mg: 10.0 },
  { b: "CUBA", n: "Cuba Blueberry Strong", mg: 20.0 },
  { b: "CUBA", n: "Cuba Cherry Strong", mg: 20.0 },
  { b: "CUBA", n: "Cuba Cola Strong", mg: 20.0 },
  { b: "CUBA", n: "Cuba Forest Berries Strong", mg: 20.0 },
  { b: "CUBA", n: "Cuba Ninja Strawberry", mg: 20.0 },
  { b: "DENSSI", n: "DENSSI Cold Mint", mg: 10.0 },
  { b: "DENSSI", n: "DENSSI Spearmint", mg: 10.0 },
  { b: "DENSSI", n: "DENSSI Strawberry Freeze", mg: 10.0 },
  { b: "DOPE", n: "Dope Freeze Strong Edition", mg: 11.2 },
  { b: "DOPE", n: "Dope Ice Cool Xtra Strong", mg: 11.2 },
  { b: "DOPE", n: "Dope Mango", mg: 11.2 },
  { b: "FEDRS", n: "Fedrs Ice Cool Cinnamon Roll", mg: 32.5 },
  { b: "FEDRS", n: "Fedrs Ice Cool Irish Coffee", mg: 32.5 },
  { b: "Fix", n: "Fix Blueberry", mg: 8.0 },
  { b: "Fix", n: "Fix Forest Fruit", mg: 11.5 },
  { b: "Fix", n: "Fix Lime", mg: 5.6 },
  { b: "Fix", n: "Fix Pomegranate", mg: 7.0 },
  { b: "Fix", n: "Fix Sweet Mint Lemon", mg: 8.0 },
  { b: "FUMI", n: "Fumi Fieri Mango", mg: 8.0 },
  { b: "FUMI", n: "Fumi Freezy Mint", mg: 8.0 },
  { b: "FUMI", n: "Fumi Minty Blueberry", mg: 8.0 },
  { b: "FUMI", n: "Fumi Prickly Pear", mg: 8.0 },
  { b: "FUMI", n: "Fumi Tangy Apple", mg: 8.0 },
  { b: "FUMI", n: "Fumi Tangy Strawberry", mg: 8.0 },
  { b: "FUMI", n: "Fumi Zingy Ginger", mg: 8.0 },
  { b: "FUZION", n: "Fuzion Berry Strong", mg: 18.0 },
  { b: "FUZION", n: "Fuzion Max Extreme", mg: 30.0 },
  { b: "FUZION", n: "Fuzion Orange Energy", mg: 16.0 },
  { b: "GARANT", n: "Garant Extreme Mint", mg: 25.0 },
  { b: "GARANT", n: "Garant Strong Plus", mg: 20.0 },
  { b: "GARANT", n: "Garant White Strong", mg: 15.0 },
  { b: "GOAT", n: "Goat Blueberry #12", mg: 8.4 },
  { b: "GOAT", n: "Goat Frosted Strong", mg: 11.5 },
  { b: "GOAT", n: "Goat White", mg: 5.6 },
  { b: "GRITT", n: "Gritt Crisp Ice Extra Strong", mg: 11.0 },
  { b: "GRITT", n: "Gritt Frost Bite", mg: 11.2 },
  { b: "GRITT", n: "Gritt Kiwi Green Apple", mg: 12.0 },
  { b: "Grant", n: "Grant Dragon Fruit", mg: 12.0 },
  { b: "Grant", n: "Grant Extreme Edition", mg: 24.0 },
  { b: "Grant", n: "Grant ICE Peach", mg: 20.0 },
  { b: "Grant", n: "Grant Licorice", mg: 9.6 },
  { b: "Grant", n: "Grant Mango Lime Extreme Edition", mg: 24.0 },
  { b: "Grant", n: "Grant Mint Slim", mg: 10.9 },
  { b: "Grant", n: "Grant Wild Berries", mg: 12.0 },
  { b: "Greatest", n: "Greatest Berry Punch", mg: 8.0 },
  { b: "Greatest", n: "Greatest Cold Dry", mg: 12.0 },
  { b: "ICEBERG", n: "Iceberg Arasaka", mg: 12.0 },
  { b: "ICEBERG", n: "Iceberg Danger Strong", mg: 25.0 },
  { b: "ICEBERG", n: "Iceberg Dragon Fruit", mg: 25.0 },
  { b: "ICEBERG", n: "Iceberg Extreme", mg: 20.0 },
  { b: "ICEBERG", n: "Iceberg Grape", mg: 25.0 },
  { b: "ICEBERG", n: "Iceberg Mango Banana", mg: 25.0 },
  { b: "ICEBERG", n: "Iceberg Medium", mg: 12.0 },
  { b: "ICEBERG", n: "Iceberg Watermelon Lime", mg: 25.0 },
  { b: "KICK", n: "Kick Strong Mint", mg: 8.0 },
  { b: "KILLA", n: "Killa 13", mg: 12.8 },
  { b: "KILLA", n: "Killa Blueberry", mg: 12.8 },
  { b: "KILLA", n: "Killa Cold Mint", mg: 12.8 },
  { b: "KILLA", n: "Killa Cold X Mint", mg: 18.0 },
  { b: "KILLA", n: "Killa Cola", mg: 12.8 },
  { b: "KILLA", n: "Killa Mini Cold Mint", mg: 8.0 },
  { b: "KILLA", n: "Killa Spearmint", mg: 12.8 },
  { b: "KILLA", n: "Killa Watermelon", mg: 13.2 },
  { b: "KLINT", n: "Klint Arctic Mint X-Strong", mg: 14.0 },
  { b: "KLINT", n: "Klint Fresh Mint Strong", mg: 10.0 },
  { b: "KLINT", n: "Klint Freeze Mint", mg: 10.0 },
  { b: "KLINT", n: "Klint Liquorice", mg: 5.6 },
  { b: "KLINT", n: "Klint Polar Mint", mg: 8.0 },
  { b: "KLINT", n: "Klint Rosé", mg: 5.0 },
  { b: "KURWA", n: "Kurwa Cocopilada", mg: 12.0 },
  { b: "KURWA", n: "Kurwa Collection Blackcurrant Purple Grape", mg: 12.0 },
  { b: "KURWA", n: "Kurwa Collection Just Berries Forest Berries", mg: 12.0 },
  { b: "KURWA", n: "Kurwa Mango Juicy", mg: 12.0 },
  { b: "LIV", n: "Liv X-Strong Mint", mg: 14.0 },
  { b: "Loop", n: "Loop Licorice Fusion Extra Strong", mg: 11.0 },
  { b: "LYFT", n: "LYFT Berry Frost", mg: 8.0 },
  { b: "LYFT", n: "LYFT Mint Slim", mg: 10.0 },
  { b: "LYFT", n: "LYFT Tropical Slim", mg: 6.0 },
  { b: "NICO", n: "Nico Citrus Crush", mg: 8.0 },
  { b: "NICO", n: "Nico Ice Rock", mg: 8.0 },
  { b: "NOIS", n: "Nois Black Edition (slabší)", mg: 4.0 },
  { b: "NOIS", n: "Nois Cool Strong", mg: 17.5 },
  { b: "NOIS", n: "Nois White Edition (silnější)", mg: 10.0 },
  { b: "NOX", n: "NOX Cool Mint", mg: 16.0 },
  { b: "NOX", n: "NOX Tropical", mg: 16.0 },
  { b: "ON!", n: "ON! Citrus 3 mg", mg: 3.0 },
  { b: "ON!", n: "ON! Citrus 6 mg", mg: 6.0 },
  { b: "ON!", n: "ON! Coffee 6 mg", mg: 6.0 },
  { b: "ON!", n: "ON! Licorice 6 mg", mg: 6.0 },
  { b: "ON!", n: "ON! Mint 3 mg", mg: 3.0 },
  { b: "ON!", n: "ON! Mint 6 mg", mg: 6.0 },
  { b: "PABLO", n: "Pablo Gold Edition Frosted Mint", mg: 25.0 },
  { b: "PABLO", n: "Pablo Ice Cold", mg: 12.0 },
  { b: "PABLO", n: "Pablo Mini Ice Cold", mg: 8.3 },
  { b: "PABLO", n: "Pablo X-Ice Cold", mg: 25.0 },
  { b: "PABLO", n: "Pablo X-Mint", mg: 16.0 },
  { b: "PUFF & POUCH", n: "Puff & Pouch Mint Blast", mg: 6.0 },
  { b: "PUFF & POUCH", n: "Puff & Pouch Red Energy", mg: 8.0 },
  { b: "R4VE kofeinové", n: "R4VE Energy Bubble Gun", mg: 0.0 },
  { b: "R4VE kofeinové", n: "R4VE Energy Mango Django", mg: 0.0 },
  { b: "R4VE kofeinové", n: "R4VE Energy Minty Berry", mg: 0.0 },
  { b: "R4VE kofeinové", n: "R4VE Energy Skiddler", mg: 0.0 },
  { b: "R4VE nikotinové", n: "R4VE Bubble Gun", mg: 10.0 },
  { b: "R4VE nikotinové", n: "R4VE Melon Strong", mg: 10.0 },
  { b: "R4VE nikotinové", n: "R4VE Red Berries", mg: 8.0 },
  { b: "Siberia", n: "Siberia Mint", mg: 6.0 },
  { b: "Siberia", n: "Siberia Spearmint Strong", mg: 9.6 },
  { b: "Siberia", n: "Siberia -80°C White Dry", mg: 34.0 },
  { b: "Siberia", n: "Siberia White Dry Regular", mg: 33.0 },
  { b: "SNATCH", n: "Snatch Arctic Mint X-Strong", mg: 16.0 },
  { b: "SNATCH", n: "Snatch Citrus Strong Edition", mg: 16.0 },
  { b: "SNATCH", n: "Snatch Forest Fruits", mg: 16.0 },
  { b: "SNATCH", n: "Snatch Frozen Ultra Strong", mg: 30.0 },
  { b: "SYX", n: "SYX Blueberry", mg: 8.0 },
  { b: "SYX", n: "SYX Low", mg: 2.8 },
  { b: "SYX", n: "SYX Medium", mg: 5.6 },
  { b: "SYX", n: "SYX Royal Wintergreen Strong", mg: 11.5 },
  { b: "Velo", n: "Velo Breezy Mango Slim", mg: 11.6 },
  { b: "Velo", n: "Velo Bright Spearmint Mini", mg: 6.0 },
  { b: "Velo", n: "Velo Cherry Ice Mini", mg: 4.0 },
  { b: "Velo", n: "Velo Cinnamon Flame Slim", mg: 10.9 },
  { b: "Velo", n: "Velo Crispy Peppermint Slim", mg: 9.8 },
  { b: "Velo", n: "Velo Crispy Peppermint Zero Slim", mg: 0.0 },
  { b: "Velo", n: "Velo Eucalyptus Storm Slim", mg: 14.0 },
  { b: "Velo", n: "Velo Freezing Peppermint Slim", mg: 10.9 },
  { b: "Velo", n: "Velo Groovy Grape Slim", mg: 10.9 },
  { b: "Velo", n: "Velo Icy Berries Mini", mg: 6.0 },
  { b: "Velo", n: "Velo McLaren Papaya Slim", mg: 8.4 },
  { b: "Velo", n: "Velo Orange Spark Slim", mg: 10.9 },
  { b: "Velo", n: "Velo Peppermint Storm Slim", mg: 10.9 },
  { b: "Velo", n: "Velo Simply Spearmint Mini", mg: 4.0 },
  { b: "Velo", n: "Velo Strawberry Ice Mini", mg: 6.0 },
  { b: "Velo", n: "Velo Strawberry Ice Slim", mg: 10.9 },
  { b: "Velo", n: "Velo Tangy Lime Slim", mg: 9.8 },
  { b: "Velo", n: "Velo Tropic Breeze Zero Slim", mg: 0.0 },
  { b: "Velo", n: "Velo Watermelon Ice Slim", mg: 8.1 },
  { b: "ZYN", n: "ZYN Citrus 3mg", mg: 3.0 },
  { b: "ZYN", n: "ZYN Citrus 6mg", mg: 6.0 },
  { b: "ZYN", n: "ZYN Cool Mint 3mg", mg: 3.0 },
  { b: "ZYN", n: "ZYN Cool Mint 6mg", mg: 6.0 },
  { b: "ZYN", n: "ZYN Spearmint 3mg", mg: 3.0 },
  { b: "ZYN", n: "ZYN Spearmint 6mg", mg: 6.0 },
  { b: "ZYN", n: "ZYN Wintergreen 3mg", mg: 3.0 },
  { b: "ZYN", n: "ZYN Wintergreen 6mg", mg: 6.0 },
  { b: "On!", n: "On! Citrus 2mg", mg: 2.0 },
  { b: "On!", n: "On! Citrus 4mg", mg: 4.0 },
  { b: "On!", n: "On! Citrus 8mg", mg: 8.0 },
  { b: "On!", n: "On! Mint 2mg", mg: 2.0 },
  { b: "On!", n: "On! Mint 4mg", mg: 4.0 },
  { b: "On!", n: "On! Mint 8mg", mg: 8.0 },
  { b: "Rogue", n: "Rogue Wintergreen 3mg", mg: 3.0 },
  { b: "Rogue", n: "Rogue Wintergreen 6mg", mg: 6.0 },
  { b: "Rogue", n: "Rogue Spearmint 3mg", mg: 3.0 },
  { b: "Rogue", n: "Rogue Spearmint 6mg", mg: 6.0 },
  { b: "Rogue", n: "Rogue Mango 3mg", mg: 3.0 },
  { b: "Rogue", n: "Rogue Mango 6mg", mg: 6.0 },
  { b: "Rogue", n: "Rogue Peppermint 3mg", mg: 3.0 },
  { b: "Rogue", n: "Rogue Peppermint 6mg", mg: 6.0 },
  { b: "VELO", n: "VELO Wintergreen 4mg", mg: 4.0 },
  { b: "VELO", n: "VELO Wintergreen 7mg", mg: 7.0 },
  { b: "VELO Plus", n: "VELO Plus Wintergreen 3mg", mg: 3.0 },
  { b: "VELO Plus", n: "VELO Plus Wintergreen 6mg", mg: 6.0 },
  { b: "VELO Plus", n: "VELO Plus Wintergreen 9mg", mg: 9.0 },
  { b: "Lucy", n: "Lucy Wintergreen 4mg", mg: 4.0 },
  { b: "Lucy", n: "Lucy Wintergreen 8mg", mg: 8.0 },
  { b: "Lucy", n: "Lucy Wintergreen 12mg", mg: 12.0 },
  { b: "Lucy", n: "Lucy Mint 4mg", mg: 4.0 },
  { b: "Lucy", n: "Lucy Mint 8mg", mg: 8.0 },
  { b: "Lucy", n: "Lucy Mint 12mg", mg: 12.0 },
  { b: "Juice Head", n: "Juice Head Watermelon Strawberry Mint 6mg", mg: 6.0 },
  { b: "Juice Head", n: "Juice Head Watermelon Strawberry Mint 12mg", mg: 12.0 },
  { b: "Juice Head", n: "Juice Head Mango Strawberry Mint 6mg", mg: 6.0 },
  { b: "Juice Head", n: "Juice Head Mango Strawberry Mint 12mg", mg: 12.0 },
  { b: "FRE", n: "FRE Mint 3mg", mg: 3.0 },
  { b: "FRE", n: "FRE Mint 6mg", mg: 6.0 },
  { b: "FRE", n: "FRE Mint 9mg", mg: 9.0 },
  { b: "FRE", n: "FRE Mint 12mg", mg: 12.0 },
  { b: "FRE", n: "FRE Mint 15mg", mg: 15.0 },
  { b: "Sesh+", n: "Sesh Mint 4mg", mg: 4.0 },
  { b: "Sesh+", n: "Sesh Mint 6mg", mg: 6.0 },
  { b: "Sesh+", n: "Sesh Mint 8mg", mg: 8.0 },
  { b: "Loop", n: "Loop Smooth Mint 9.4mg", mg: 9.4 },
  { b: "Loop", n: "Loop Smooth Mint 12.5mg", mg: 12.5 },
  { b: "Loop", n: "Loop Smooth Mint 15.6mg", mg: 15.6 },
  { b: "XQS", n: "XQS Mint 4mg", mg: 4.0 },
  { b: "XQS", n: "XQS Mint 10mg", mg: 10.0 },
  { b: "ALP", n: "ALP Chilled Mint 3mg", mg: 3.0 },
  { b: "ALP", n: "ALP Chilled Mint 6mg", mg: 6.0 },
  { b: "ALP", n: "ALP Chilled Mint 9mg", mg: 9.0 },
  { b: "ALP", n: "ALP Tropical Fruit 3mg", mg: 3.0 },
  { b: "ALP", n: "ALP Tropical Fruit 6mg", mg: 6.0 },
  { b: "ALP", n: "ALP Tropical Fruit 9mg", mg: 9.0 },
  { b: "STNG", n: "STNG Mint Regular 9.2mg", mg: 9.2 },
  { b: "STNG", n: "STNG Mint MAX 27.5mg", mg: 27.5 },
  { b: "STNG", n: "STNG Berry Seltzer Regular 9.2mg", mg: 9.2 },
  { b: "STNG", n: "STNG Berry Seltzer MAX 27.5mg", mg: 27.5 },
  { b: "Chapo", n: "Chapo Brutal Cold 6mg", mg: 6.0 },
  { b: "Chapo", n: "Chapo Brutal Cold 13.2mg", mg: 13.2 },
  { b: "Chapo", n: "Chapo Crystal Menthol 6mg", mg: 6.0 },
  { b: "Chapo", n: "Chapo Crystal Menthol 13.2mg", mg: 13.2 },
  { b: "Chapo", n: "Chapo Watermelon Strong 13.2mg", mg: 13.2 },
  { b: "ZYN", n: "ZYN Citrus 3mg", mg: 3.0 },
  { b: "ZYN", n: "ZYN Citrus 6mg", mg: 6.0 },
  { b: "ZYN", n: "ZYN Cool Mint 3mg", mg: 3.0 },
  { b: "ZYN", n: "ZYN Cool Mint 6mg", mg: 6.0 },
  { b: "VELO", n: "VELO Wintergreen 4mg", mg: 4.0 },
  { b: "VELO", n: "VELO Wintergreen 7mg", mg: 7.0 },
  { b: "VELO Plus", n: "VELO Plus Wintergreen 3mg", mg: 3.0 },
  { b: "VELO Plus", n: "VELO Plus Wintergreen 6mg", mg: 6.0 },
  { b: "VELO Plus", n: "VELO Plus Wintergreen 9mg", mg: 9.0 },
  { b: "Nordic Spirit", n: "Nordic Spirit Spearmint 6mg", mg: 6.0 },
  { b: "Nordic Spirit", n: "Nordic Spirit Spearmint 9mg", mg: 9.0 },
  { b: "Nordic Spirit", n: "Nordic Spirit Frosty Berry 11mg", mg: 11.0 },
  { b: "ZYN", n: "ZYN Cinnamon 3mg", mg: 3.0 },
  { b: "ZYN", n: "ZYN Cinnamon 6mg", mg: 6.0 },
  { b: "ZYN", n: "ZYN Coffee 3mg", mg: 3.0 },
  { b: "ZYN", n: "ZYN Coffee 6mg", mg: 6.0 },
  { b: "ZYN", n: "ZYN Black Currant Ice Super Strong", mg: 8.0 },
  { b: "ZYN", n: "ZYN Cool Mint Ice Ultra Strong", mg: 10.0 },
  { b: "Helwit", n: "Helwit Mint 4mg", mg: 4.0 },
  { b: "Helwit", n: "Helwit Mint 7.5mg Extra Strong", mg: 7.5 },
  { b: "Helwit", n: "Helwit Blueberry 4mg", mg: 4.0 },
  { b: "Helwit", n: "Helwit Blueberry Extra Strong 7.5mg", mg: 7.5 },
  { b: "Helwit", n: "Helwit Mocha 4mg", mg: 4.0 },
  { b: "Helwit", n: "Helwit Mocha Extra Strong 7.5mg", mg: 7.5 },
  { b: "Helwit", n: "Helwit Cola 4mg", mg: 4.0 },
  { b: "Helwit", n: "Helwit Cola Extra Strong 7.5mg", mg: 7.5 },
  { b: "Helwit", n: "Helwit Banana 4mg", mg: 4.0 },
  { b: "Helwit", n: "Helwit Banana Extra Strong 7.5mg", mg: 7.5 },
  { b: "Helwit", n: "Helwit Violet 4mg", mg: 4.0 },
  { b: "Helwit", n: "Helwit Violet Extra Strong 7.5mg", mg: 7.5 },
  { b: "ZEUS", n: "Zeus Mint Rage 25mg", mg: 25.0 },
  { b: "ZEUS", n: "Zeus Frozen Citrus 25mg", mg: 25.0 },
  { b: "ZEUS", n: "Zeus Tropic Burst 25mg", mg: 25.0 },
  { b: "ZEUS", n: "Zeus Cherry Blossom 25mg", mg: 25.0 },
  { b: "ZEUS", n: "Zeus Epic Berry 25mg", mg: 25.0 },
  { b: "ZEUS", n: "Zeus Arctic Freeze 25mg", mg: 25.0 },
  { b: "SKRUF", n: "Skruf Super White Fresh Mint 12mg", mg: 12.0 },
  { b: "SKRUF", n: "Skruf Super White Fresh Freeze Ultra Strong 16mg", mg: 16.0 },
  { b: "VELO", n: "VELO Cinnamon 4mg", mg: 4.0 },
  { b: "VELO", n: "VELO Cinnamon 7mg", mg: 7.0 },
  { b: "VELO", n: "VELO Black Cherry 4mg", mg: 4.0 },
  { b: "VELO", n: "VELO Black Cherry 7mg", mg: 7.0 },
  { b: "VELO", n: "VELO Coffee 4mg", mg: 4.0 },
  { b: "VELO", n: "VELO Coffee 7mg", mg: 7.0 },
  { b: "VELO Plus", n: "VELO Plus Cinnamon 3mg", mg: 3.0 },
  { b: "VELO Plus", n: "VELO Plus Cinnamon 6mg", mg: 6.0 },
  { b: "VELO Plus", n: "VELO Plus Cinnamon 9mg", mg: 9.0 },
  { b: "VELO Plus", n: "VELO Plus Wild Berry 3mg", mg: 3.0 },
  { b: "VELO Plus", n: "VELO Plus Wild Berry 6mg", mg: 6.0 },
  { b: "VELO Plus", n: "VELO Plus Wild Berry 9mg", mg: 9.0 },
  { b: "VELO Plus", n: "VELO Plus Citrus Chill 3mg", mg: 3.0 },
  { b: "VELO Plus", n: "VELO Plus Citrus Chill 6mg", mg: 6.0 },
  { b: "VELO Plus", n: "VELO Plus Citrus Chill 9mg", mg: 9.0 },
  { b: "VELO Plus", n: "VELO Plus Dragon Fruit 3mg", mg: 3.0 },
  { b: "VELO Plus", n: "VELO Plus Dragon Fruit 6mg", mg: 6.0 },
  { b: "VELO Plus", n: "VELO Plus Dragon Fruit 9mg", mg: 9.0 },
  { b: "VELO Plus", n: "VELO Plus Watermelon Chill 3mg", mg: 3.0 },
  { b: "VELO Plus", n: "VELO Plus Watermelon Chill 6mg", mg: 6.0 },
  { b: "VELO Plus", n: "VELO Plus Watermelon Chill 9mg", mg: 9.0 },
  { b: "VELO Plus", n: "VELO Plus Tropical Heat 3mg", mg: 3.0 },
  { b: "VELO Plus", n: "VELO Plus Tropical Heat 6mg", mg: 6.0 },
  { b: "VELO Plus", n: "VELO Plus Tropical Heat 9mg", mg: 9.0 },
  { b: "VELO Plus", n: "VELO Plus Cappuccino 3mg", mg: 3.0 },
  { b: "VELO Plus", n: "VELO Plus Cappuccino 6mg", mg: 6.0 },
  { b: "VELO Plus", n: "VELO Plus Cappuccino 9mg", mg: 9.0 },
  { b: "Nor", n: "Nor No.4 Strawberry", mg: 12.0 },
  { b: "Nor", n: "Nor No.10 Peach", mg: 8.0 },
  { b: "Nor", n: "Nor No.2 Peppermint", mg: 16.0 },
  { b: "LOOP", n: "LOOP Blueberry Ice Strong", mg: 9.0 },
  { b: "VELO Shift", n: "VELO Shift Hot Peach Strong", mg: 11.0 },
  { b: "VELO Shift", n: "VELO Shift Cool Peppermint Strong", mg: 11.0 },
  { b: "KILLA", n: "KILLA Cherry Cola", mg: 13.0 },
  { b: "KILLA", n: "KILLA Cola", mg: 11.0 },
  { b: "KILLA", n: "KILLA Mango Ice", mg: 11.0 },
  { b: "KILLA", n: "KILLA Double Dutch Cold", mg: 11.0 },
  { b: "KILLA", n: "KILLA Blue Mint", mg: 12.0 },
  { b: "PABLO", n: "PABLO Gold Edition Frosted Mint", mg: 17.0 },
  { b: "PABLO", n: "PABLO Gold Edition Grape Ice", mg: 17.0 },
  { b: "PABLO", n: "PABLO Gold Edition Passion Fruit", mg: 17.0 },
  { b: "PABLO", n: "PABLO Gold Edition Kiwi", mg: 17.0 },
  { b: "PABLO", n: "PABLO Gold Edition Blue Raspberry", mg: 17.0 },
  { b: "NOIS", n: "NOIS Cherry Ice", mg: 12.0 },
  { b: "NOIS", n: "NOIS Eucalypt", mg: 12.0 },
  { b: "NOIS", n: "NOIS Cool Strong", mg: 17.0 },
  { b: "NOIS", n: "NOIS Spearmint", mg: 10.0 },
  { b: "Helwit", n: "Helwit Watermelon", mg: 3.0 },
  { b: "Helwit", n: "Helwit Wintermint", mg: 4.0 },
  { b: "Valkyria", n: "Valkyria Pictish Spearmint Slim", mg: 9.0 },
  { b: "ZYN", n: "ZYN Cactus Spice Slim Limited Edition", mg: 11.0 },
  { b: "VELO", n: "VELO Icy Cherry", mg: 8.0 },
  { b: "DENSSI", n: "DENSSI Watermelon Freeze", mg: 6.0 },
  { b: "DENSSI", n: "DENSSI Cool Mint", mg: 11.0 },
  { b: "DENSSI", n: "DENSSI Brain Freeze", mg: 18.0 },
  { b: "DENSSI", n: "DENSSI Spearmint", mg: 16.0 },
  { b: "DENSSI", n: "DENSSI Strawberry Freeze", mg: 16.0 },
  { b: "Sesh+", n: "Sesh Wintergreen 6mg", mg: 6.0 },
  { b: "Sesh+", n: "Sesh Wintergreen 8mg", mg: 8.0 },
  { b: "Sesh+", n: "Sesh Cappuccino 4mg", mg: 4.0 },
  { b: "Sesh+", n: "Sesh Cappuccino 6mg", mg: 6.0 },
  { b: "Sesh+", n: "Sesh Cappuccino 8mg", mg: 8.0 },
  { b: "Sesh+", n: "Sesh Mango 4mg", mg: 4.0 },
  { b: "Sesh+", n: "Sesh Mango 6mg", mg: 6.0 },
  { b: "Sesh+", n: "Sesh Mango 8mg", mg: 8.0 },
  { b: "Sesh+", n: "Sesh Clear 4mg", mg: 4.0 },
  { b: "Sesh+", n: "Sesh Clear 6mg", mg: 6.0 },
  { b: "Sesh+", n: "Sesh Clear 8mg", mg: 8.0 },
  { b: "Loop", n: "Loop Jalapeño Lime 9.4mg", mg: 9.4 },
  { b: "Loop", n: "Loop Jalapeño Lime 12.5mg", mg: 12.5 },
  { b: "Loop", n: "Loop Jalapeño Lime 15.6mg", mg: 15.6 },
  { b: "Loop", n: "Loop Red Chili Melon 9.4mg", mg: 9.4 },
  { b: "Loop", n: "Loop Red Chili Melon 12.5mg", mg: 12.5 },
  { b: "Loop", n: "Loop Red Chili Melon 15.6mg", mg: 15.6 },
  { b: "Loop", n: "Loop Strawberry Ice 9.4mg", mg: 9.4 },
  { b: "Loop", n: "Loop Strawberry Ice 12.5mg", mg: 12.5 },
  { b: "Loop", n: "Loop Strawberry Ice 15.6mg", mg: 15.6 },
  { b: "XQS", n: "XQS Blueberry Mint 4mg", mg: 4.0 },
  { b: "XQS", n: "XQS Blueberry Mint 10mg", mg: 10.0 },
  { b: "XQS", n: "XQS Citrus Cooling 4mg", mg: 4.0 },
  { b: "XQS", n: "XQS Citrus Cooling 10mg", mg: 10.0 },
  { b: "XQS", n: "XQS Black Cherry 4mg", mg: 4.0 },
  { b: "XQS", n: "XQS Black Cherry 10mg", mg: 10.0 },
  { b: "Helwit", n: "Helwit Mint 4mg", mg: 4.0 },
  { b: "Helwit", n: "Helwit Mint 7.5mg Extra Strong", mg: 7.5 },
  { b: "Helwit", n: "Helwit Blueberry 4mg", mg: 4.0 },
  { b: "Helwit", n: "Helwit Blueberry Extra Strong 7.5mg", mg: 7.5 },
  { b: "Helwit", n: "Helwit Mocha 4mg", mg: 4.0 },
  { b: "Helwit", n: "Helwit Cola 4mg", mg: 4.0 },
  { b: "ZEUS", n: "Zeus Mint Rage 25mg", mg: 25.0 },
  { b: "ZEUS", n: "Zeus Frozen Citrus 25mg", mg: 25.0 },
  { b: "ZEUS", n: "Zeus Tropic Burst 25mg", mg: 25.0 },
  { b: "ZEUS", n: "Zeus Cherry Blossom 25mg", mg: 25.0 },
  { b: "SKRUF", n: "Skruf Super White Fresh Mint 12mg", mg: 12.0 },
  { b: "SKRUF", n: "Skruf Super White Fresh Freeze Ultra Strong 16mg", mg: 16.0 },
  { b: "Lucy", n: "Lucy Mint 4mg", mg: 4.0 },
  { b: "Lucy", n: "Lucy Mint 8mg", mg: 8.0 },
  { b: "Lucy", n: "Lucy Mint 12mg", mg: 12.0 },
  { b: "Lucy", n: "Lucy Wintergreen 4mg", mg: 4.0 },
  { b: "FRE", n: "FRE Mint 3mg", mg: 3.0 },
  { b: "FRE", n: "FRE Mint 6mg", mg: 6.0 },
  { b: "FRE", n: "FRE Mint 12mg", mg: 12.0 },
  { b: "FRE", n: "FRE Mint 15mg", mg: 15.0 },
  { b: "Juice Head", n: "Juice Head Watermelon Strawberry Mint 6mg", mg: 6.0 },
  { b: "Juice Head", n: "Juice Head Watermelon Strawberry Mint 12mg", mg: 12.0 },
  { b: "Juice Head", n: "Juice Head Mango Strawberry Mint 6mg", mg: 6.0 },
  { b: "Juice Head", n: "Juice Head Mango Strawberry Mint 12mg", mg: 12.0 },
  { b: "Rogue", n: "Rogue Wintergreen 3mg", mg: 3.0 },
  { b: "Rogue", n: "Rogue Wintergreen 6mg", mg: 6.0 },
  { b: "Rogue", n: "Rogue Spearmint 3mg", mg: 3.0 },
  { b: "Rogue", n: "Rogue Spearmint 6mg", mg: 6.0 },
  { b: "On!", n: "On! Wintergreen", mg: 2.0 },
  { b: "FRE", n: "FRE Watermelon 12MG", mg: 12.0 },
  { b: "VELO", n: "Velo Plus Tropical Heat 6MG", mg: 6.0 },
  { b: "SESH", n: "Sesh+ Cappuccino 6mg", mg: 6.0 },
  { b: "CLEW", n: "CLEW Blueberry 6mg", mg: 6.0 },
  { b: "ZYN", n: "ZYN Espresso Martini 6MG", mg: 6.0 },
  { b: "ZYN", n: "ZYN Mojito 6MG", mg: 6.0 },
  { b: "ZYN", n: "ZYN Spiced Cider 6MG", mg: 6.0 },
  { b: "ZYN", n: "ZYN Espresso Martini 3MG", mg: 3.0 },
  { b: "ZYN", n: "ZYN Spiced Cider 3MG", mg: 3.0 },
  { b: "ZYN", n: "ZYN Mojito 3MG", mg: 3.0 },
  { b: "ZYN", n: "ZYN Wintergreen 6MG", mg: 6.0 },
  { b: "ZYN", n: "ZYN Cool Mint 6MG", mg: 6.0 },
  { b: "ZYN", n: "ZYN Spearmint 6MG", mg: 6.0 },
  { b: "ZYN", n: "ZYN Peppermint 6MG", mg: 6.0 },
  { b: "VELO", n: "Velo Plus Spearmint 3MG", mg: 3.0 },
  { b: "VELO", n: "Velo Plus Peppermint 3MG", mg: 3.0 },
  { b: "Rogue", n: "Rogue Wintergreen 6MG", mg: 6.0 },
  { b: "ZYN", n: "ZYN Wintergreen 3MG", mg: 3.0 },
  { b: "ZYN", n: "ZYN Citrus 3MG", mg: 3.0 },
  { b: "ZYN", n: "ZYN Cool Mint 3MG", mg: 3.0 },
  { b: "FRE", n: "FRE Watermelon 9MG", mg: 9.0 },
  { b: "VELO", n: "Velo Plus Wintergreen 6MG", mg: 6.0 },
  { b: "Grizzly", n: "Grizzly Hunter Orange 12MG", mg: 12.0 },
  { b: "Grizzly", n: "Grizzly Copperhead 12MG", mg: 12.0 },
  { b: "ALP", n: "ALP Mint 3.0", mg: 3.0 },
  { b: "ALP", n: "ALP Mint 9.0", mg: 9.0 },
  { b: "ALP", n: "ALP Wintergreen 6.0", mg: 6.0 },
  { b: "ALP", n: "ALP Unflavored 3.0", mg: 3.0 },
  { b: "ALP", n: "ALP Coffee 9.0", mg: 9.0 },
  { b: "Juice Head", n: "Juice Head Mango 12.0", mg: 12.0 },
  { b: "Juice Head", n: "Juice Head Apple 6.0", mg: 6.0 },
  { b: "Juice Head", n: "Juice Head Watermelon 6.0", mg: 6.0 },
  { b: "Juice Head", n: "Juice Head Raspberry 12.0", mg: 12.0 },
  { b: "Juice Head", n: "Juice Head Mango 6.0", mg: 6.0 },
  { b: "On!", n: "On! Wintergreen 2.0", mg: 2.0 },
  { b: "On!", n: "On! Wintergreen 4.0", mg: 4.0 },
  { b: "On!", n: "On! Wintergreen 8.0", mg: 8.0 },
  { b: "On!", n: "On! Mint 2.0", mg: 2.0 },
  { b: "On!", n: "On! Mint 4.0", mg: 4.0 },
  { b: "On!", n: "On! Mint 8.0", mg: 8.0 },
  { b: "On!", n: "On! Cinnamon 2.0", mg: 2.0 },
  { b: "On!", n: "On! Cinnamon 4.0", mg: 4.0 },
  { b: "On!", n: "On! Cinnamon 8.0", mg: 8.0 },
  { b: "On!", n: "On! Coffee 2.0", mg: 2.0 },
  { b: "On!", n: "On! Coffee 4.0", mg: 4.0 },
  { b: "On!", n: "On! Coffee 8.0", mg: 8.0 },
  { b: "On!", n: "On! Citrus 2.0", mg: 2.0 },
  { b: "On!", n: "On! Citrus 4.0", mg: 4.0 },
  { b: "On!", n: "On! Citrus 8.0", mg: 8.0 },
  { b: "On!", n: "On! Berry 2.0", mg: 2.0 },
  { b: "On!", n: "On! Berry 4.0", mg: 4.0 },
  { b: "On!", n: "On! Berry 8.0", mg: 8.0 },
  { b: "On!", n: "On! Original 2.0", mg: 2.0 },
  { b: "On!", n: "On! Original 4.0", mg: 4.0 },
  { b: "On!", n: "On! Original 8.0", mg: 8.0 },
  { b: "Rogue", n: "Rogue Wintergreen 3.0", mg: 3.0 },
  { b: "Rogue", n: "Rogue Wintergreen 6.0", mg: 6.0 },
  { b: "Rogue", n: "Rogue Cinnamon 6.0", mg: 6.0 },
  { b: "Rogue", n: "Rogue Coffee 3.0", mg: 3.0 },
  { b: "Rogue", n: "Rogue Peach 6.0", mg: 6.0 },
  { b: "Rogue", n: "Rogue Berry 3.0", mg: 3.0 },
  { b: "Rogue", n: "Rogue Spearmint 6.0", mg: 6.0 },
  { b: "Rogue", n: "Rogue Peppermint 3.0", mg: 3.0 },
  { b: "Rogue", n: "Rogue Unflavored 6.0", mg: 6.0 },
  { b: "FRE", n: "FRE Mint 3.0", mg: 3.0 },
  { b: "FRE", n: "FRE Mint 6.0", mg: 6.0 },
  { b: "FRE", n: "FRE Watermelon 3.0", mg: 3.0 },
  { b: "FRE", n: "FRE Watermelon 6.0", mg: 6.0 },
  { b: "FRE", n: "FRE Watermelon 15.0", mg: 15.0 },
  { b: "FRE", n: "FRE Spearmint 3.0", mg: 3.0 },
  { b: "FRE", n: "FRE Spearmint 6.0", mg: 6.0 },
  { b: "FRE", n: "FRE Berry 3.0", mg: 3.0 },
  { b: "FRE", n: "FRE Berry 12.0", mg: 12.0 },
  { b: "CLEW", n: "CLEW Mint 3.0", mg: 3.0 },
  { b: "CLEW", n: "CLEW Mint 6.0", mg: 6.0 },
  { b: "CLEW", n: "CLEW Mint 9.0", mg: 9.0 },
  { b: "CLEW", n: "CLEW Mint 12.0", mg: 12.0 },
  { b: "CLEW", n: "CLEW Blueberry 3.0", mg: 3.0 },
  { b: "CLEW", n: "CLEW Blueberry 9.0", mg: 9.0 },
  { b: "CLEW", n: "CLEW Wintergreen 6.0", mg: 6.0 },
  { b: "CLEW", n: "CLEW Coffee 3.0", mg: 3.0 },
  { b: "CLEW", n: "CLEW Coffee 12.0", mg: 12.0 },
  { b: "ZYN", n: "ZYN Wintergreen 6.0", mg: 6.0 },
  { b: "ZYN", n: "ZYN Cool Mint 6.0", mg: 6.0 },
  { b: "ZYN", n: "ZYN Citrus 3.0", mg: 3.0 },
  { b: "VELO", n: "VELO Wintergreen 6.0", mg: 6.0 },
  { b: "VELO", n: "VELO Cool Mint 4.0", mg: 4.0 },
  { b: "VELO", n: "VELO Fresh Mint 7.0", mg: 7.0 },
  { b: "Rogue", n: "Rogue Wintergreen 6.0", mg: 6.0 },
  { b: "Rogue", n: "Rogue Wintergreen 3.0", mg: 3.0 },
  { b: "Rogue", n: "Rogue Cinnamon 6.0", mg: 6.0 },
  { b: "Rogue", n: "Rogue Citrus 3.0", mg: 3.0 },
  { b: "On!", n: "On! Wintergreen 4.0", mg: 4.0 },
  { b: "On!", n: "On! Cool Mint 4.0", mg: 4.0 },
  { b: "On!", n: "On! Cinnamon 8.0", mg: 8.0 },
  { b: "FRE", n: "FRE Mint 6.0", mg: 6.0 },
  { b: "FRE", n: "FRE Watermelon 12.0", mg: 12.0 },
  { b: "Lucy", n: "Lucy Mint 4.0", mg: 4.0 },
  { b: "Lucy", n: "Lucy Watermelon 8.0", mg: 8.0 },
  { b: "CLEW", n: "CLEW Mint 6.0", mg: 6.0 },
  { b: "CLEW", n: "CLEW Blueberry 9.0", mg: 9.0 },
  { b: "KUMA", n: "KUMA Blood Orange 11mg", mg: 11.0 },
  { b: "KUMA", n: "KUMA Banana Toffee 11mg", mg: 11.0 },
  { b: "KUMA", n: "KUMA Cherry 11mg", mg: 11.0 },
  { b: "KUMA", n: "KUMA Wintergreen 11mg", mg: 11.0 },
  { b: "Après", n: "Après Blueberry Mini 3mg", mg: 3.0 },
  { b: "Après", n: "Après Blueberry Extra Strong 8mg", mg: 8.0 },
  { b: "Après", n: "Après Blueberry Hyper Strong 11mg", mg: 11.0 },
  { b: "Après", n: "Après Blueberry Regular 4mg", mg: 4.0 },
  { b: "Après", n: "Après Bananas Mini 3mg", mg: 3.0 },
  { b: "Après", n: "Après Bananas Extra Strong 8mg", mg: 8.0 },
  { b: "Après", n: "Après Bananas Hyper Strong 11mg", mg: 11.0 },
  { b: "Après", n: "Après Bananas Regular 4mg", mg: 4.0 },
  { b: "Après", n: "Après Tangerine Spritz Mini 3mg", mg: 3.0 },
  { b: "Après", n: "Après Tangerine Spritz Extra Strong 8mg", mg: 8.0 },
  { b: "Après", n: "Après Tangerine Spritz Hyper Strong 11mg", mg: 11.0 },
  { b: "Après", n: "Après Tangerine Spritz Regular 4mg", mg: 4.0 },
  { b: "Après", n: "Après Cactus Lime Mini 3mg", mg: 3.0 },
  { b: "Après", n: "Après Cactus Lime Extra Strong 8mg", mg: 8.0 },
  { b: "Après", n: "Après Cactus Lime Hyper Strong 11mg", mg: 11.0 },
  { b: "Après", n: "Après Cactus Lime Regular 4mg", mg: 4.0 },
  { b: "Après", n: "Après Raspberry Licorice Mini 3mg", mg: 3.0 },
  { b: "Après", n: "Après Raspberry Licorice Extra Strong 8mg", mg: 8.0 },
  { b: "Après", n: "Après Raspberry Licorice Hyper Strong 11mg", mg: 11.0 },
  { b: "Après", n: "Après Raspberry Licorice Regular 4mg", mg: 4.0 },
  { b: "Après", n: "Après Very Berry Regular 4mg", mg: 4.0 },
  { b: "Après", n: "Après Ice Tea Peach Mini 3mg", mg: 3.0 },
  { b: "Après", n: "Après Ice Tea Peach Extra Strong 8mg", mg: 8.0 },
  { b: "Après", n: "Après Ice Tea Peach Hyper Strong 11mg", mg: 11.0 },
  { b: "Après", n: "Après Ice Tea Peach Regular 4mg", mg: 4.0 },
  { b: "Après", n: "Après Cola Extra Strong 8mg", mg: 8.0 },
  { b: "Après", n: "Après Cola Hyper Strong 11mg", mg: 11.0 },
  { b: "Après", n: "Après Cola Regular 4mg", mg: 4.0 },
  { b: "LOOP", n: "LOOP Jalapeño Mini", mg: 9.0 },
  { b: "LOOP", n: "LOOP Jalapeño Mini Strong", mg: 12.0 },
  { b: "LOOP", n: "LOOP Jalapeño Mini X-Strong", mg: 15.0 },
  { b: "LOOP", n: "LOOP Red Chili Mini", mg: 9.0 },
  { b: "LOOP", n: "LOOP Red Chili Mini Strong", mg: 12.0 },
  { b: "LOOP", n: "LOOP Red Chili Mini X-Strong", mg: 15.0 },
  { b: "LOOP", n: "LOOP Strawberry Mini", mg: 9.0 },
  { b: "LOOP", n: "LOOP Strawberry Mini Strong", mg: 12.0 },
  { b: "PABLO", n: "PABLO Blueberry Light", mg: 8.0 },
  { b: "PABLO", n: "PABLO Blueberry Regular", mg: 13.0 },
  { b: "PABLO", n: "PABLO Blueberry Strong", mg: 16.0 },
  { b: "PABLO", n: "PABLO Mint Light", mg: 8.0 },
  { b: "PABLO", n: "PABLO Mint Regular", mg: 13.0 },
  { b: "PABLO", n: "PABLO Mint Strong", mg: 16.0 },
  { b: "PABLO", n: "PABLO Cherry Light", mg: 8.0 },
  { b: "PABLO", n: "PABLO Cherry Regular", mg: 13.0 },
  { b: "GREATEST", n: "GREATEST Cold Dry", mg: 12.0 },
  { b: "GREATEST", n: "GREATEST Freeze", mg: 12.0 },
  { b: "GREATEST", n: "GREATEST Lemon", mg: 12.0 },
  { b: "GREATEST", n: "GREATEST Mango", mg: 12.0 },
  { b: "DENSSI", n: "DENSSI Watermelon Freeze", mg: 6.0 },
  { b: "DENSSI", n: "DENSSI Cold Mint", mg: 11.0 },
  { b: "DENSSI", n: "DENSSI Brain Freeze", mg: 18.0 },
  { b: "DENSSI", n: "DENSSI Spearmint", mg: 16.0 },
  { b: "DENSSI", n: "DENSSI Strawberry Freeze", mg: 16.0 },
  { b: "HELWIT", n: "HELWIT Banana Extra Strong", mg: 8.0 },
  { b: "HELWIT", n: "HELWIT Peppermint Strong", mg: 10.0 },
  { b: "ACE", n: "ACE Cool Mint", mg: 6.0 },
  { b: "ACE", n: "ACE Eucalyptus", mg: 6.0 },
  { b: "ACE", n: "ACE Extreme Cool", mg: 11.0 },
  { b: "ACE", n: "ACE Green Lemon", mg: 6.0 },
  { b: "ACE", n: "ACE X EXTEND Cool Mint", mg: 10.0 },
  { b: "AROMa KING", n: "AROMa KING Full Kick Candy Tobacco", mg: 10.0 },
  { b: "AROMa KING", n: "AROMa KING Full Kick Double Mint", mg: 10.0 },
  { b: "AROMa KING", n: "AROMa KING Soft Kick Candy Tobacco", mg: 5.0 },
  { b: "AROMa KING", n: "AROMa KING Soft Kick Double Mint", mg: 5.0 },
  { b: "CLEW", n: "CLEW Mango Mint", mg: 10.0 },
  { b: "CLEW", n: "CLEW Watermelon Ice", mg: 10.0 },
  { b: "FIX", n: "FIX Blueberry", mg: 8.0 },
  { b: "FIX", n: "FIX Forest Fruit", mg: 11.0 },
  { b: "FIX", n: "FIX Lime", mg: 5.0 },
  { b: "FIX", n: "FIX Pomegranate", mg: 7.0 },
  { b: "FIX", n: "FIX Sweet Mint Lemon", mg: 8.0 },
  { b: "FUMI", n: "FUMI Fieri Mango", mg: 8.0 },
  { b: "FUMI", n: "FUMI Freezy Mint", mg: 8.0 },
  { b: "FUMI", n: "FUMI Minty Blueberry", mg: 8.0 },
  { b: "FUMI", n: "FUMI Prickly Pear", mg: 8.0 },
  { b: "FUMI", n: "FUMI Tangy Apple", mg: 8.0 },
  { b: "FUMI", n: "FUMI Tangy Strawberry", mg: 8.0 },
  { b: "FUMI", n: "FUMI Zingy Ginger", mg: 8.0 },
  { b: "CUBA", n: "CUBA Double Fresh Black", mg: 16.0 },
  { b: "VELO", n: "VELO Limited Edition Midsummer Sweet Blackcurrant", mg: 8.0 },
  { b: "VELO", n: "VELO McLaren Sweet Papaya", mg: 8.0 },
  { b: "HELWIT", n: "Helwit Menthol Slim", mg: 6.0 },
  { b: "HELWIT", n: "Helwit Cola Extra Strong", mg: 7.5 },
  { b: "HELWIT", n: "Helwit Violet Extra Strong", mg: 7.5 },
  { b: "HELWIT", n: "Helwit Orange Slim", mg: 4.5 },
  { b: "HELWIT", n: "Helwit Cherry Slim", mg: 4.5 },
  { b: "HELWIT", n: "Helwit Blueberry Extra Strong", mg: 7.5 },
  { b: "HELWIT", n: "Helwit Pear Slim", mg: 4.5 },
  { b: "HELWIT", n: "Helwit Salmiak Slim Strong", mg: 6.0 },
  { b: "HELWIT", n: "Helwit Mint Slim", mg: 3.5 },
  { b: "HELWIT", n: "Helwit Cola Slim", mg: 3.5 },
  { b: "HELWIT", n: "Helwit Violet Slim", mg: 3.5 },
  { b: "HELWIT", n: "Helwit Blueberry Slim", mg: 4.5 },
  { b: "LOOP", n: "LOOP Smooth Mint Extra Strong", mg: 11.0 },
  { b: "LOOP", n: "LOOP Smooth Mint Strong", mg: 9.0 },
  { b: "LOOP", n: "LOOP Smooth Mint Mini", mg: 6.0 },
  { b: "LOOP", n: "LOOP Spicy Apple Strong", mg: 9.0 },
  { b: "LOOP", n: "LOOP Red Chili Melon Hyper Strong", mg: 15.0 },
  { b: "LOOP", n: "LOOP Red Chili Melon Extra Strong", mg: 11.0 },
  { b: "LOOP", n: "LOOP Red Chili Melon Strong", mg: 9.0 },
  { b: "LOOP", n: "LOOP Red Chili Melon Normal", mg: 6.0 },
  { b: "LOOP", n: "LOOP Red Chili Melon Mini", mg: 6.0 },
  { b: "LOOP", n: "LOOP Licorice Fusion Extra Strong", mg: 11.0 },
  { b: "LOOP", n: "LOOP Licorice Fusion Strong", mg: 9.0 },
  { b: "LOOP", n: "LOOP Jalapeno Lime Slim Hyper Strong", mg: 15.0 },
  { b: "LOOP", n: "LOOP Jalapeno Lime Extra Strong", mg: 11.0 },
  { b: "LOOP", n: "LOOP Jalapeno Lime Normal", mg: 6.0 },
  { b: "LOOP", n: "LOOP Jalapeno Lime Strong", mg: 9.0 },
  { b: "LOOP", n: "LOOP Jalapeno Lime Mini", mg: 6.0 },
  { b: "LOOP", n: "LOOP Ice Cool Mint Strong", mg: 11.0 },
  { b: "LOOP", n: "LOOP Hot Rhubarb Strong", mg: 11.0 },
  { b: "LOOP", n: "LOOP Hot Peach Strong", mg: 9.0 },
  { b: "LOOP", n: "LOOP Habanero Mint Extra Strong", mg: 11.0 },
  { b: "LOOP", n: "LOOP Habanero Mint Slim Hyper Strong", mg: 15.0 },
  { b: "LOOP", n: "LOOP Hot Mango Strong", mg: 9.0 },
  { b: "LOOP", n: "LOOP Creamy Cappuccino Strong", mg: 9.0 },
  { b: "LOOP", n: "LOOP Cassis Bliss Slim Strong", mg: 9.0 },
  { b: "ZYN", n: "ZYN Menthol Ice Slim", mg: 13.5 },
  { b: "ZYN", n: "ZYN Cool Frost Slim Strong", mg: 9.0 },
  { b: "ZYN", n: "ZYN Violet Licorice Slim", mg: 9.0 },
  { b: "ZYN", n: "ZYN Apple Mint Slim Strong", mg: 9.0 },
  { b: "ZYN", n: "ZYN Lemon Spritz Slim Normal", mg: 6.0 },
  { b: "ZYN", n: "ZYN Citrus Slim Strong", mg: 9.0 },
  { b: "ZYN", n: "ZYN Cool Frost Slim Extra Strong", mg: 11.0 },
  { b: "ZYN", n: "ZYN Violet Licorice Slim Normal", mg: 6.0 },
  { b: "ZYN", n: "ZYN Red Fruits Slim", mg: 6.0 },
  { b: "ZYN", n: "ZYN Exotic Mango Mini Normal", mg: 6.0 },
  { b: "Pablo", n: "Pablo Mini X-Ice Cold", mg: 40.0 },
  { b: "Pablo", n: "Pablo Mini Ice Cold", mg: 40.0 },
  { b: "Pablo", n: "Pablo Mini Red", mg: 40.0 },
  { b: "Pablo", n: "Pablo Exclusive Strawberry Cheesecake", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Frosted Ice", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Dark Cherry", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Cherry Cola", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Orange", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Strawberry Watermelon", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Passion Fruit", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Blue Mint", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Cappuccino", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Mango Ice", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Grape Ice", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Tropical Punch", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Mocca", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Strawberry Lychee", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Bubblegum", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Pear", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Liquorice", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Green Mint", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Lemonade", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Blue Raspberry", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Banana Ice", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Frosted Mint", mg: 50.0 },
  { b: "Pablo", n: "Pablo Dry Ice Cold", mg: 40.0 },
  { b: "Pablo", n: "Pablo Dry X-Ice Cold", mg: 40.0 },
  { b: "Pablo", n: "Pablo Dry Red", mg: 40.0 },
  { b: "Pablo", n: "Pablo Ice Cold XXL", mg: 40.0 },
  { b: "Pablo", n: "Pablo RED 16g", mg: 40.0 },
  { b: "Pablo", n: "Pablo Ice Cold 16g", mg: 40.0 },
  { b: "Pablo", n: "Pablo X-Ice Cold 16g", mg: 40.0 },
  { b: "ZYN", n: "ZYN Apple Mint Mini 3mg", mg: 3.0 },
  { b: "ZYN", n: "ZYN Apple Mint Mini 6mg", mg: 6.0 },
  { b: "ZYN", n: "ZYN Black Cherry Mini 3mg", mg: 3.0 },
  { b: "ZYN", n: "ZYN Black Cherry Mini 6mg", mg: 6.0 },
  { b: "ZYN", n: "ZYN Peach Mini 3mg", mg: 3.0 },
  { b: "ZYN", n: "ZYN Spearmint Mini 1.5mg", mg: 1.5 },
  { b: "ZYN", n: "ZYN Citrus Mini 3mg", mg: 3.0 },
  { b: "ZYN", n: "ZYN Cool Mint Mini 6mg", mg: 6.0 },
  { b: "ZYN", n: "ZYN Cool Mint Mini 3mg", mg: 3.0 },
  { b: "ZYN", n: "ZYN Coffee Mini 3mg", mg: 3.0 },
  { b: "Royal", n: "Royal White Gin and Grapefruit", mg: 11.0 },
  { b: "Pablo", n: "Pablo Gold Edition Frosted Ice", mg: 17.0 },
  { b: "Pablo", n: "Pablo Gold Edition Dark Cherry", mg: 17.0 },
  { b: "Pablo", n: "Pablo Gold Edition White Mint", mg: 17.0 },
  { b: "Pablo", n: "Pablo Exclusive Strawberry Kiwi", mg: 50.0 },
  { b: "Pablo", n: "Pablo Exclusive Blueberry Peach", mg: 50.0 },
  { b: "Killa", n: "Killa Pineapple", mg: 11.0 },
  { b: "White Fox", n: "White Fox Mint Slim", mg: 12.0 },
  { b: "White Fox", n: "White Fox Double Mint", mg: 12.0 },
  { b: "White Fox", n: "White Fox Peppered Mint", mg: 12.0 },
  { b: "White Fox", n: "White Fox Full Charge", mg: 16.5 },
  { b: "White Fox", n: "White Fox Black Edition", mg: 12.0 },

  // --- White Fox (additional) ---
  { b: "White Fox", n: "White Fox Dry Mint", mg: 6.5 },
  { b: "White Fox", n: "White Fox Crushed Ice", mg: 12.0 },
  { b: "White Fox", n: "White Fox Ice Cold", mg: 16.5 },

  // --- SHIRO (Philip Morris AB, Sweden) ---
  { b: "SHIRO", n: "Shiro Cool Mint Regular", mg: 3.6 },
  { b: "SHIRO", n: "Shiro Cool Mint Strong", mg: 6.0 },
  { b: "SHIRO", n: "Shiro Cool Mint Extra Strong", mg: 11.0 },
  { b: "SHIRO", n: "Shiro Virginia Classic Regular", mg: 3.6 },
  { b: "SHIRO", n: "Shiro Virginia Classic Strong", mg: 6.0 },
  { b: "SHIRO", n: "Shiro Virginia Classic Extra Strong", mg: 11.0 },
  { b: "SHIRO", n: "Shiro Sweet Mint Strong", mg: 6.0 },
  { b: "SHIRO", n: "Shiro Sour Red Berry Extra Strong", mg: 11.0 },
  { b: "SHIRO", n: "Shiro Tingling Mint Hyper Strong", mg: 15.5 },
  { b: "SHIRO", n: "Shiro Cooling Mint Extra Strong", mg: 11.0 },

  // --- EPOK (V2 Tobacco / Norway) ---
  { b: "EPOK", n: "Epok Mint", mg: 8.5 },
  { b: "EPOK", n: "Epok Licorice", mg: 8.5 },
  { b: "EPOK", n: "Epok Blueberry", mg: 8.5 },
  { b: "EPOK", n: "Epok Lime", mg: 8.5 },
  { b: "EPOK", n: "Epok Melon", mg: 8.5 },
  { b: "EPOK", n: "Epok Coffee", mg: 8.5 },
  { b: "EPOK", n: "Epok Juniper", mg: 8.5 },

  // --- THUNDER (V2 Tobacco, Denmark) ---
  { b: "THUNDER", n: "Thunder Frosted", mg: 13.0 },
  { b: "THUNDER", n: "Thunder Dark Frost", mg: 13.0 },
  { b: "THUNDER", n: "Thunder Deep Freeze", mg: 16.0 },
  { b: "THUNDER", n: "Thunder Slim White Frosted", mg: 16.0 },

  // --- NICK & JOHNNY (Swedish Match) ---
  { b: "NICK & JOHNNY", n: "Nick & Johnny Crushed Ice", mg: 12.0 },
  { b: "NICK & JOHNNY", n: "Nick & Johnny Spicy Mix", mg: 12.0 },
  { b: "NICK & JOHNNY", n: "Nick & Johnny Deep Freeze", mg: 16.0 },
  { b: "NICK & JOHNNY", n: "Nick & Johnny Wintry Mix", mg: 12.0 },

  // --- G.4 (Swedish Match) ---
  { b: "G.4", n: "G.4 Cryo Slim", mg: 10.0 },
  { b: "G.4", n: "G.4 Fu:zn Apple Mint", mg: 10.0 },
  { b: "G.4", n: "G.4 Ice Cold Mint", mg: 12.0 },

  // --- HIT (GN Tobacco, Sweden) ---
  { b: "HIT", n: "Hit Blueberry", mg: 20.0 },
  { b: "HIT", n: "Hit Orange", mg: 20.0 },
  { b: "HIT", n: "Hit Mint", mg: 20.0 },
  { b: "HIT", n: "Hit Watermelon", mg: 20.0 },
  { b: "HIT", n: "Hit Cola", mg: 20.0 },

  // --- ELF (Elf Bar Nicotine Pouches) ---
  { b: "ELF", n: "Elf Blueberry Raspberry", mg: 6.0 },
  { b: "ELF", n: "Elf Blueberry Raspberry Strong", mg: 12.0 },
  { b: "ELF", n: "Elf Blueberry Raspberry Ultra", mg: 20.0 },
  { b: "ELF", n: "Elf Grape Ice", mg: 6.0 },
  { b: "ELF", n: "Elf Grape Ice Strong", mg: 12.0 },
  { b: "ELF", n: "Elf Grape Ice Ultra", mg: 20.0 },
  { b: "ELF", n: "Elf Cool Storm", mg: 6.0 },
  { b: "ELF", n: "Elf Cool Storm Strong", mg: 12.0 },
  { b: "ELF", n: "Elf Cool Storm Ultra", mg: 20.0 },
  { b: "ELF", n: "Elf Fantasy Orange", mg: 6.0 },
  { b: "ELF", n: "Elf Fantasy Orange Strong", mg: 12.0 },
  { b: "ELF", n: "Elf Watermelon Ice", mg: 6.0 },
  { b: "ELF", n: "Elf Watermelon Ice Ultra", mg: 20.0 },
  { b: "ELF", n: "Elf Max Polar Mint", mg: 12.0 },
  { b: "ELF", n: "Elf Max Polar Mint Ultra", mg: 20.0 },

  // --- TACJA (Elf Bar / Miracle, Sweden) ---
  { b: "TACJA", n: "Tacja Cool Mint Regular", mg: 12.0 },
  { b: "TACJA", n: "Tacja Cool Mint Medium", mg: 18.0 },
  { b: "TACJA", n: "Tacja Cool Mint Strong", mg: 20.0 },
  { b: "TACJA", n: "Tacja Spearmint Regular", mg: 12.0 },
  { b: "TACJA", n: "Tacja Spearmint Strong", mg: 20.0 },
  { b: "TACJA", n: "Tacja Tropical Mango Regular", mg: 12.0 },
  { b: "TACJA", n: "Tacja Tropical Mango Strong", mg: 20.0 },
  { b: "TACJA", n: "Tacja Blueberry Regular", mg: 12.0 },
  { b: "TACJA", n: "Tacja Blueberry Strong", mg: 20.0 },
  { b: "TACJA", n: "Tacja Watermelon Ice Regular", mg: 12.0 },
  { b: "TACJA", n: "Tacja Strawberry Kiwi Regular", mg: 12.0 },
  { b: "TACJA", n: "Tacja Grape Ice Medium", mg: 18.0 },

  // --- EXTREME (N.G.P Empire, Lithuania) ---
  { b: "EXTREME", n: "Extreme Fruit Vibes", mg: 20.0 },
  { b: "EXTREME", n: "Extreme Fruit Vibes Max", mg: 30.0 },
  { b: "EXTREME", n: "Extreme Mint Blast", mg: 20.0 },
  { b: "EXTREME", n: "Extreme Mint Blast Max", mg: 30.0 },
  { b: "EXTREME", n: "Extreme Lime Rush", mg: 20.0 },
  { b: "EXTREME", n: "Extreme Lime Rush Max", mg: 30.0 },
  { b: "EXTREME", n: "Extreme Berry Bomb", mg: 20.0 },

  // --- ZONE (US) ---
  { b: "ZONE", n: "Zone Spearmint 6mg", mg: 6.0 },
  { b: "ZONE", n: "Zone Spearmint 9mg", mg: 9.0 },
  { b: "ZONE", n: "Zone Wintergreen 6mg", mg: 6.0 },
  { b: "ZONE", n: "Zone Wintergreen 9mg", mg: 9.0 },
  { b: "ZONE", n: "Zone Citrus 6mg", mg: 6.0 },
  { b: "ZONE", n: "Zone Citrus 9mg", mg: 9.0 },
  { b: "ZONE", n: "Zone Peppermint 6mg", mg: 6.0 },
  { b: "ZONE", n: "Zone Peppermint 9mg", mg: 9.0 },
  { b: "ZONE", n: "Zone Mint 6mg", mg: 6.0 },
  { b: "ZONE", n: "Zone Mint 9mg", mg: 9.0 },
  { b: "ZONE", n: "Zone Dragonfruit 6mg", mg: 6.0 },
  { b: "ZONE", n: "Zone Dragonfruit 9mg", mg: 9.0 },

  // --- ZEO Universe (US, international) ---
  { b: "ZEO", n: "Zeo Mint Breeze 4mg", mg: 4.0 },
  { b: "ZEO", n: "Zeo Mint Breeze 6mg", mg: 6.0 },
  { b: "ZEO", n: "Zeo Mint Breeze 12mg", mg: 12.0 },
  { b: "ZEO", n: "Zeo Wintergreen Ice 4mg", mg: 4.0 },
  { b: "ZEO", n: "Zeo Wintergreen Ice 6mg", mg: 6.0 },
  { b: "ZEO", n: "Zeo Wintergreen Ice 12mg", mg: 12.0 },
  { b: "ZEO", n: "Zeo Menthol Evergreen 4mg", mg: 4.0 },
  { b: "ZEO", n: "Zeo Menthol Evergreen 6mg", mg: 6.0 },
  { b: "ZEO", n: "Zeo Menthol Evergreen 12mg", mg: 12.0 },
  { b: "ZEO", n: "Zeo Pineapple Tropic 4mg", mg: 4.0 },
  { b: "ZEO", n: "Zeo Pineapple Tropic 9mg", mg: 9.0 },
  { b: "ZEO", n: "Zeo Watermelon Wave 4mg", mg: 4.0 },
  { b: "ZEO", n: "Zeo Watermelon Wave 9mg", mg: 9.0 },
  { b: "ZEO", n: "Zeo Berry Moonlight 4mg", mg: 4.0 },
  { b: "ZEO", n: "Zeo Berry Moonlight 9mg", mg: 9.0 },
  { b: "ZEO", n: "Zeo Flavor Free 4mg", mg: 4.0 },
  { b: "ZEO", n: "Zeo Flavor Free 6mg", mg: 6.0 },
  { b: "ZEO", n: "Zeo Flavor Free 12mg", mg: 12.0 },

  // --- BLACK BUFFALO (US) ---
  { b: "BLACK BUFFALO", n: "Black Buffalo Wintergreen", mg: 11.25 },
  { b: "BLACK BUFFALO", n: "Black Buffalo Mint", mg: 11.25 },
  { b: "BLACK BUFFALO", n: "Black Buffalo Straight", mg: 11.25 },
  { b: "BLACK BUFFALO", n: "Black Buffalo Blood Orange", mg: 11.25 },
  { b: "BLACK BUFFALO", n: "Black Buffalo Peach", mg: 11.25 },

  // --- BRIDGE (US) ---
  { b: "BRIDGE", n: "Bridge Cool Mint 4mg", mg: 4.0 },
  { b: "BRIDGE", n: "Bridge Cool Mint 10mg", mg: 10.0 },
  { b: "BRIDGE", n: "Bridge Cool Mint 15mg", mg: 15.0 },
  { b: "BRIDGE", n: "Bridge Wintergreen 4mg", mg: 4.0 },
  { b: "BRIDGE", n: "Bridge Wintergreen 10mg", mg: 10.0 },
  { b: "BRIDGE", n: "Bridge Wintergreen 15mg", mg: 15.0 },
  { b: "BRIDGE", n: "Bridge Spearmint 4mg", mg: 4.0 },
  { b: "BRIDGE", n: "Bridge Spearmint 10mg", mg: 10.0 },
  { b: "BRIDGE", n: "Bridge Spearmint 15mg", mg: 15.0 },
  { b: "BRIDGE", n: "Bridge Citrus 4mg", mg: 4.0 },
  { b: "BRIDGE", n: "Bridge Citrus 10mg", mg: 10.0 },
  { b: "BRIDGE", n: "Bridge Citrus 15mg", mg: 15.0 },
  { b: "BRIDGE", n: "Bridge Original 4mg", mg: 4.0 },
  { b: "BRIDGE", n: "Bridge Original 10mg", mg: 10.0 },
  { b: "BRIDGE", n: "Bridge Original 15mg", mg: 15.0 },

  // --- MONK ---
  { b: "MONK", n: "Monk Dragon Fruit Regular", mg: 12.0 },
  { b: "MONK", n: "Monk Dragon Fruit Strong", mg: 20.0 },
  { b: "MONK", n: "Monk Wild Berries Regular", mg: 12.0 },
  { b: "MONK", n: "Monk Wild Berries Strong", mg: 20.0 },
  { b: "MONK", n: "Monk Classic Mint Regular", mg: 12.0 },
  { b: "MONK", n: "Monk Classic Mint Strong", mg: 20.0 },
  { b: "MONK", n: "Monk Tropical Fruit Regular", mg: 12.0 },
  { b: "MONK", n: "Monk Tropical Fruit Strong", mg: 20.0 },
  { b: "MONK", n: "Monk Apple Cider Regular", mg: 12.0 },
  { b: "MONK", n: "Monk Apple Cider Strong", mg: 20.0 },
  { b: "MONK", n: "Monk Strawberry Lemonade Regular", mg: 12.0 },
  { b: "MONK", n: "Monk Strawberry Lemonade Strong", mg: 20.0 },
  { b: "MONK", n: "Monk Very Berry Strong", mg: 20.0 },
  { b: "MONK", n: "Monk Cola Strong", mg: 20.0 },

  // --- GRIZZLY (additional) ---
  { b: "Grizzly", n: "Grizzly Wintergreen 7mg", mg: 7.0 },
  { b: "Grizzly", n: "Grizzly Peppermint 7mg", mg: 7.0 },
  { b: "Grizzly", n: "Grizzly Spearmint 7mg", mg: 7.0 },
  { b: "Grizzly", n: "Grizzly Buckshot Coffee 12mg", mg: 12.0 },
  { b: "Grizzly", n: "Grizzly Backcountry Dark Fruits 12mg", mg: 12.0 },

  // --- ROGUE (additional flavors) ---
  { b: "Rogue", n: "Rogue Honey Lemon 3mg", mg: 3.0 },
  { b: "Rogue", n: "Rogue Honey Lemon 6mg", mg: 6.0 },
  { b: "Rogue", n: "Rogue Apple 3mg", mg: 3.0 },
  { b: "Rogue", n: "Rogue Apple 6mg", mg: 6.0 },
  { b: "Rogue", n: "Rogue Citrus 6mg", mg: 6.0 },
  { b: "Rogue", n: "Rogue Tabac 3mg", mg: 3.0 },
  { b: "Rogue", n: "Rogue Tabac 6mg", mg: 6.0 },

  // --- LUCY (additional flavors) ---
  { b: "Lucy", n: "Lucy Apple Ice 4mg", mg: 4.0 },
  { b: "Lucy", n: "Lucy Apple Ice 8mg", mg: 8.0 },
  { b: "Lucy", n: "Lucy Apple Ice 12mg", mg: 12.0 },
  { b: "Lucy", n: "Lucy Mango 4mg", mg: 4.0 },
  { b: "Lucy", n: "Lucy Mango 8mg", mg: 8.0 },
  { b: "Lucy", n: "Lucy Mango 12mg", mg: 12.0 },
  { b: "Lucy", n: "Lucy Berry Citrus 4mg", mg: 4.0 },
  { b: "Lucy", n: "Lucy Berry Citrus 8mg", mg: 8.0 },
  { b: "Lucy", n: "Lucy Berry Citrus 12mg", mg: 12.0 },
  { b: "Lucy", n: "Lucy Espresso 4mg", mg: 4.0 },
  { b: "Lucy", n: "Lucy Espresso 8mg", mg: 8.0 },
  { b: "Lucy", n: "Lucy Espresso 12mg", mg: 12.0 },
  { b: "Lucy", n: "Lucy Cinnamon 4mg", mg: 4.0 },
  { b: "Lucy", n: "Lucy Cinnamon 8mg", mg: 8.0 },
  { b: "Lucy", n: "Lucy Cinnamon 12mg", mg: 12.0 },

  // --- JUICE HEAD (additional flavors) ---
  { b: "Juice Head", n: "Juice Head Raspberry Lemonade Mint 6mg", mg: 6.0 },
  { b: "Juice Head", n: "Juice Head Raspberry Lemonade Mint 12mg", mg: 12.0 },
  { b: "Juice Head", n: "Juice Head Peach Pineapple Mint 6mg", mg: 6.0 },
  { b: "Juice Head", n: "Juice Head Peach Pineapple Mint 12mg", mg: 12.0 },
  { b: "Juice Head", n: "Juice Head Blueberry Lemon Mint 6mg", mg: 6.0 },
  { b: "Juice Head", n: "Juice Head Blueberry Lemon Mint 12mg", mg: 12.0 },

  // --- KLINT (additional flavors) ---
  { b: "KLINT", n: "Klint Lavender", mg: 5.0 },
  { b: "KLINT", n: "Klint Lavender Strong", mg: 8.0 },
  { b: "KLINT", n: "Klint Rose", mg: 5.0 },
  { b: "KLINT", n: "Klint Rose Strong", mg: 8.0 },
  { b: "KLINT", n: "Klint Honeymelon", mg: 5.0 },
  { b: "KLINT", n: "Klint Honeymelon Strong", mg: 8.0 },
  { b: "KLINT", n: "Klint Cola Lime", mg: 5.0 },
  { b: "KLINT", n: "Klint Cola Lime Strong", mg: 10.0 },
  { b: "KLINT", n: "Klint Pink Grapefruit", mg: 5.0 },
  { b: "KLINT", n: "Klint Pink Grapefruit Strong", mg: 8.0 },
  { b: "KLINT", n: "Klint Pomegranate", mg: 5.0 },
  { b: "KLINT", n: "Klint Pomegranate Strong", mg: 8.0 },
  { b: "KLINT", n: "Klint Spicy Ginger", mg: 5.0 },
  { b: "KLINT", n: "Klint Spicy Ginger Strong", mg: 8.0 },

  // --- VALKYRIA (additional) ---
  { b: "Valkyria", n: "Valkyria Viking Maiden Peach Slim", mg: 4.5 },
  { b: "Valkyria", n: "Valkyria Viking Maiden Peach Strong", mg: 6.0 },
  { b: "Valkyria", n: "Valkyria Viking Maiden Peach X-Strong", mg: 9.0 },

  // --- SKRUF (additional) ---
  { b: "SKRUF", n: "Skruf Super White Slim Northern Lights", mg: 11.0 },
  { b: "SKRUF", n: "Skruf Super White Slim Polar Mint", mg: 11.0 },
  { b: "SKRUF", n: "Skruf Super White Slim Tropical Guava", mg: 11.0 },
  { b: "SKRUF", n: "Skruf Super White Slim Barberry Cotton", mg: 8.5 },
  { b: "SKRUF", n: "Skruf Super White Slim Menthol", mg: 8.5 },
  { b: "SKRUF", n: "Skruf Super White Slim X-Strong Fresh Mint", mg: 19.0 },

  // --- ÜBBS (UK) ---
  { b: "ÜBBS", n: "ÜBBS Berry 6mg", mg: 6.0 },
  { b: "ÜBBS", n: "ÜBBS Berry 12mg", mg: 12.0 },
  { b: "ÜBBS", n: "ÜBBS Berry 20mg", mg: 20.0 },
  { b: "ÜBBS", n: "ÜBBS Mango 6mg", mg: 6.0 },
  { b: "ÜBBS", n: "ÜBBS Mango 12mg", mg: 12.0 },
  { b: "ÜBBS", n: "ÜBBS Mango 20mg", mg: 20.0 },
  { b: "ÜBBS", n: "ÜBBS Peppermint 6mg", mg: 6.0 },
  { b: "ÜBBS", n: "ÜBBS Peppermint 12mg", mg: 12.0 },
  { b: "ÜBBS", n: "ÜBBS Peppermint 20mg", mg: 20.0 },
  { b: "ÜBBS", n: "ÜBBS Cherry 6mg", mg: 6.0 },
  { b: "ÜBBS", n: "ÜBBS Cherry 12mg", mg: 12.0 },
  { b: "ÜBBS", n: "ÜBBS Cherry 20mg", mg: 20.0 },
  { b: "ÜBBS", n: "ÜBBS Watermelon 6mg", mg: 6.0 },
  { b: "ÜBBS", n: "ÜBBS Watermelon 12mg", mg: 12.0 },
  { b: "ÜBBS", n: "ÜBBS Peach Passion 6mg", mg: 6.0 },
  { b: "ÜBBS", n: "ÜBBS Peach Passion 12mg", mg: 12.0 },
  { b: "ÜBBS", n: "ÜBBS Salted Caramel 6mg", mg: 6.0 },
  { b: "ÜBBS", n: "ÜBBS Salted Caramel 12mg", mg: 12.0 },
  { b: "ÜBBS", n: "ÜBBS Cola Ice 6mg", mg: 6.0 },
  { b: "ÜBBS", n: "ÜBBS Cola Ice 12mg", mg: 12.0 },
  { b: "ÜBBS", n: "ÜBBS Menthol 6mg", mg: 6.0 },
  { b: "ÜBBS", n: "ÜBBS Menthol 12mg", mg: 12.0 },

  // --- KLAR ---
  { b: "KLAR", n: "Klar Mint 3mg", mg: 3.0 },
  { b: "KLAR", n: "Klar Mint 6mg", mg: 6.0 },
  { b: "KLAR", n: "Klar Mint 9mg", mg: 9.0 },
  { b: "KLAR", n: "Klar Citrus 3mg", mg: 3.0 },
  { b: "KLAR", n: "Klar Citrus 6mg", mg: 6.0 },
  { b: "KLAR", n: "Klar Citrus 9mg", mg: 9.0 },
  { b: "KLAR", n: "Klar Unflavored 3mg", mg: 3.0 },
  { b: "KLAR", n: "Klar Unflavored 6mg", mg: 6.0 },
  { b: "KLAR", n: "Klar Unflavored 9mg", mg: 9.0 },
  { b: "KLAR", n: "Klar Oolong Melon 10mg", mg: 10.0 },

  // --- NIXS ---
  { b: "NIXS", n: "Nixs Icy Mint Regular", mg: 6.0 },
  { b: "NIXS", n: "Nixs Icy Mint Strong", mg: 11.0 },
  { b: "NIXS", n: "Nixs Salmiak Regular", mg: 6.0 },
  { b: "NIXS", n: "Nixs Melon Rush Regular", mg: 6.0 },
  { b: "NIXS", n: "Nixs Minty Lemon Regular", mg: 6.0 },

  // --- RUSH ---
  { b: "RUSH", n: "Rush Nordic Frost Regular", mg: 11.0 },
  { b: "RUSH", n: "Rush Nordic Frost Strong", mg: 21.0 },
  { b: "RUSH", n: "Rush Ice Cool Regular", mg: 11.0 },
  { b: "RUSH", n: "Rush Ice Cool Strong", mg: 21.0 },
  { b: "RUSH", n: "Rush Green Mint Regular", mg: 11.0 },
  { b: "RUSH", n: "Rush Green Mint Strong", mg: 21.0 },
  { b: "RUSH", n: "Rush Berry Ice Regular", mg: 11.0 },
  { b: "RUSH", n: "Rush Berry Ice Strong", mg: 21.0 },
  { b: "RUSH", n: "Rush Mango Freeze Regular", mg: 11.0 },
  { b: "RUSH", n: "Rush Mango Freeze Strong", mg: 21.0 },
  { b: "RUSH", n: "Rush Cherry Chill Regular", mg: 11.0 },
  { b: "RUSH", n: "Rush Icy Grape Regular", mg: 11.0 },
  { b: "RUSH", n: "Rush Watermelon Ice", mg: 10.0 },
  { b: "RUSH", n: "Rush Wintergreen 3mg", mg: 3.0 },
  { b: "RUSH", n: "Rush Wintergreen 7mg", mg: 7.0 },
  { b: "RUSH", n: "Rush Citrus 3mg", mg: 3.0 },
  { b: "RUSH", n: "Rush Cinnamon 3mg", mg: 3.0 },

  // --- Nordic Spirit (expanded) ---
  { b: "Nordic Spirit", n: "Nordic Spirit Mint Dry 6mg", mg: 6.0 },
  { b: "Nordic Spirit", n: "Nordic Spirit Mint Dry 9mg", mg: 9.0 },
  { b: "Nordic Spirit", n: "Nordic Spirit Bergamot Wildberry 6mg", mg: 6.0 },
  { b: "Nordic Spirit", n: "Nordic Spirit Bergamot Wildberry 9mg", mg: 9.0 },
  { b: "Nordic Spirit", n: "Nordic Spirit Wildberry 9mg", mg: 9.0 },
  { b: "Nordic Spirit", n: "Nordic Spirit Elderflower 6mg", mg: 6.0 },
  { b: "Nordic Spirit", n: "Nordic Spirit Sweet Mint 6mg", mg: 6.0 },
  { b: "Nordic Spirit", n: "Nordic Spirit Sweet Mint 9mg", mg: 9.0 },
  { b: "Nordic Spirit", n: "Nordic Spirit Raspberry 9mg", mg: 9.0 },
  { b: "Nordic Spirit", n: "Nordic Spirit Dark Fizz 9mg", mg: 9.0 },
  { b: "Nordic Spirit", n: "Nordic Spirit Dark Fizz Max 17mg", mg: 17.0 },
  { b: "Nordic Spirit", n: "Nordic Spirit Frosty Berry Max 17mg", mg: 17.0 },
  { b: "Nordic Spirit", n: "Nordic Spirit Frosty Mint Strong 9mg", mg: 9.0 },
  { b: "Nordic Spirit", n: "Nordic Spirit Blueberry 9mg", mg: 9.0 },
  { b: "Nordic Spirit", n: "Nordic Spirit Mocha 6mg", mg: 6.0 },
  { b: "Nordic Spirit", n: "Nordic Spirit Zesty Pear 6mg", mg: 6.0 },

  // --- ZYN (expanded EU lineup) ---
  { b: "ZYN", n: "ZYN Blueberry Mint Slim 11mg", mg: 11.0 },
  { b: "ZYN", n: "ZYN Red Fruits Slim 9mg", mg: 9.0 },
  { b: "ZYN", n: "ZYN Blackcurrant Frost Slim 13.5mg", mg: 13.5 },
  { b: "ZYN", n: "ZYN Menthol Ice Slim 16.5mg", mg: 16.5 },
  { b: "ZYN", n: "ZYN Citrus Slim Strong 9mg", mg: 9.0 },
  { b: "ZYN", n: "ZYN Citrus Slim Extra Strong 11mg", mg: 11.0 },
  { b: "ZYN", n: "ZYN Cool Frost Slim Extra Strong 11mg", mg: 11.0 },
  { b: "ZYN", n: "ZYN Red Berry Fizz 11mg", mg: 11.0 },
  { b: "ZYN", n: "ZYN Peach Mini 6mg", mg: 6.0 },
  { b: "ZYN", n: "ZYN Black Cherry 11mg", mg: 11.0 },

  // --- XQS (expanded) ---
  { b: "XQS", n: "XQS Spearmint Strong 10mg", mg: 10.0 },
  { b: "XQS", n: "XQS Arctic Freeze Extra Strong 20mg", mg: 20.0 },
  { b: "XQS", n: "XQS Fizzy Cola 4mg", mg: 4.0 },
  { b: "XQS", n: "XQS Fizzy Cola 10mg", mg: 10.0 },
  { b: "XQS", n: "XQS Chili Mango 4mg", mg: 4.0 },
  { b: "XQS", n: "XQS Chili Mango 10mg", mg: 10.0 },
  { b: "XQS", n: "XQS Cactus Sour 4mg", mg: 4.0 },
  { b: "XQS", n: "XQS Cactus Sour 10mg", mg: 10.0 },
  { b: "XQS", n: "XQS Orange Apple 4mg", mg: 4.0 },
  { b: "XQS", n: "XQS Orange Apple 10mg", mg: 10.0 },
  { b: "XQS", n: "XQS Elderflower 4mg", mg: 4.0 },
  { b: "XQS", n: "XQS Hallon Soda 10mg", mg: 10.0 },
  { b: "XQS", n: "XQS Dark Banana 10mg", mg: 10.0 },

  // --- ACE X (extended line) ---
  { b: "ACE", n: "ACE X Cosmic Cool Mint", mg: 11.6 },
  { b: "ACE", n: "ACE X Guarana Chili", mg: 11.6 },
  { b: "ACE", n: "ACE X Honeydew Blackpepper", mg: 11.6 },
  { b: "ACE", n: "ACE X Black Raspberry Chili", mg: 11.6 },
  { b: "ACE", n: "ACE X Red Apple Cinnamon", mg: 11.6 },
  { b: "ACE", n: "ACE Spearmint Slim", mg: 6.0 },

  // --- CUBA (expanded) ---
  { b: "CUBA", n: "Cuba White Cola 10.4mg", mg: 10.4 },
  { b: "CUBA", n: "Cuba White Mango 10.4mg", mg: 10.4 },
  { b: "CUBA", n: "Cuba White Watermelon 10.4mg", mg: 10.4 },
  { b: "CUBA", n: "Cuba White Forest Berries 10.4mg", mg: 10.4 },
  { b: "CUBA", n: "Cuba White Cherry 10.4mg", mg: 10.4 },
  { b: "CUBA", n: "Cuba White Peach 10.4mg", mg: 10.4 },
  { b: "CUBA", n: "Cuba White Blackberry 10.4mg", mg: 10.4 },
  { b: "CUBA", n: "Cuba White Tropical Fruit 10.4mg", mg: 10.4 },
  { b: "CUBA", n: "Cuba White Banana 10.4mg", mg: 10.4 },
  { b: "CUBA", n: "Cuba White Bubblegum 10.4mg", mg: 10.4 },
  { b: "CUBA", n: "Cuba White Coconut 10.4mg", mg: 10.4 },
  { b: "CUBA", n: "Cuba White Ice Spearmint 10.4mg", mg: 10.4 },
  { b: "CUBA", n: "Cuba White Low Cola 4mg", mg: 4.0 },
  { b: "CUBA", n: "Cuba White Low Mango 4mg", mg: 4.0 },
  { b: "CUBA", n: "Cuba White Low Watermelon 4mg", mg: 4.0 },
  { b: "CUBA", n: "Cuba Ninja Energy 16.3mg", mg: 16.3 },
  { b: "CUBA", n: "Cuba Ninja Bubblegum 16.3mg", mg: 16.3 },
  { b: "CUBA", n: "Cuba Ninja Pina Colada 16.3mg", mg: 16.3 },
  { b: "CUBA", n: "Cuba Ninja Liquorice 16.3mg", mg: 16.3 },
  { b: "CUBA", n: "Cuba Black 42.9mg", mg: 42.9 },

  // --- ICEBERG (expanded) ---
  { b: "ICEBERG", n: "Iceberg Cool Mint", mg: 12.0 },
  { b: "ICEBERG", n: "Iceberg Black Mint", mg: 20.0 },
  { b: "ICEBERG", n: "Iceberg Double Mint", mg: 20.0 },
  { b: "ICEBERG", n: "Iceberg Sweet Mint", mg: 12.0 },
  { b: "ICEBERG", n: "Iceberg Watermelon", mg: 25.0 },
  { b: "ICEBERG", n: "Iceberg Kiwi", mg: 25.0 },
  { b: "ICEBERG", n: "Iceberg Kiwi Strawberry", mg: 25.0 },
  { b: "ICEBERG", n: "Iceberg Berries", mg: 20.0 },
  { b: "ICEBERG", n: "Iceberg Blackcurrant", mg: 20.0 },
  { b: "ICEBERG", n: "Iceberg Bubble Gum", mg: 20.0 },
  { b: "ICEBERG", n: "Iceberg Gummy Bears", mg: 20.0 },
  { b: "ICEBERG", n: "Iceberg Raspberry Gum", mg: 20.0 },
  { b: "ICEBERG", n: "Iceberg Cola", mg: 20.0 },
  { b: "ICEBERG", n: "Iceberg Coconut", mg: 20.0 },
  { b: "ICEBERG", n: "Iceberg Cherry Apricot", mg: 25.0 },
  { b: "ICEBERG", n: "Iceberg Sour Berries", mg: 20.0 },
  { b: "ICEBERG", n: "Iceberg Energy", mg: 25.0 },

  // --- KILLA (expanded) ---
  { b: "KILLA", n: "Killa Frosted Mint", mg: 13.0 },
  { b: "KILLA", n: "Killa Grape Ice", mg: 13.0 },
  { b: "KILLA", n: "Killa Banana Ice", mg: 13.0 },
  { b: "KILLA", n: "Killa White Coffee", mg: 13.0 },
  { b: "KILLA", n: "Killa Classic Bubblegum", mg: 13.0 },
  { b: "KILLA", n: "Killa Strawberry Cheesecake", mg: 13.0 },
  { b: "KILLA", n: "Killa Pineapple Ice", mg: 13.0 },
  { b: "KILLA", n: "Killa Lemonade", mg: 13.0 },
  { b: "KILLA", n: "Killa Blue Raspberry Exclusive", mg: 18.0 },
  { b: "KILLA", n: "Killa Dark Cherry Exclusive", mg: 18.0 },

  // --- KURWA (expanded) ---
  { b: "KURWA", n: "Kurwa Killer Kiwi Strawberry 12mg", mg: 12.0 },
  { b: "KURWA", n: "Kurwa Killer Blueberry Marmalade 12mg", mg: 12.0 },
  { b: "KURWA", n: "Kurwa Killer Bubblegum 12mg", mg: 12.0 },
  { b: "KURWA", n: "Kurwa Killer Blackcurrant 12mg", mg: 12.0 },
  { b: "KURWA", n: "Kurwa Collection Strawberry Vanilla 12mg", mg: 12.0 },
  { b: "KURWA", n: "Kurwa Collection Cola Vanilla Cherry 12mg", mg: 12.0 },
  { b: "KURWA", n: "Kurwa Fatality Brutal Energy Drink 32mg", mg: 32.0 },
  { b: "KURWA", n: "Kurwa Fatality Tropical Cocktail 32mg", mg: 32.0 },
  { b: "KURWA", n: "Kurwa Fatality Cherry Cranberry 32mg", mg: 32.0 },
  { b: "KURWA", n: "Kurwa Fatality Cola Whisky 32mg", mg: 32.0 },
  { b: "KURWA", n: "Kurwa Fatality Lemon Lemongrass 32mg", mg: 32.0 },
  { b: "KURWA", n: "Kurwa Fatality Strawberry Cake 32mg", mg: 32.0 },
  { b: "KURWA", n: "Kurwa Fatality Brutal Blueberry 32mg", mg: 32.0 },
  { b: "KURWA", n: "Kurwa Fatality Cactus Apple 32mg", mg: 32.0 },
  { b: "KURWA", n: "Kurwa Fatality Mango Milk 32mg", mg: 32.0 },

  // --- LYFT (additional, before rebrand) ---
  { b: "LYFT", n: "Lyft Ice Cool X-Strong", mg: 15.6 },
  { b: "LYFT", n: "Lyft Licorice Strong", mg: 10.0 },
  { b: "LYFT", n: "Lyft Lime Strong", mg: 10.0 },
  { b: "LYFT", n: "Lyft Blueberry Strong", mg: 10.0 },
  { b: "LYFT", n: "Lyft Citrus Mint Strong", mg: 10.0 },
  { b: "LYFT", n: "Lyft Black Currant Strong", mg: 10.0 },
  { b: "LYFT", n: "Lyft Eucalyptus Honey Strong", mg: 10.0 },
  { b: "LYFT", n: "Lyft Tropic Breeze Slim", mg: 6.0 },
  { b: "LYFT", n: "Lyft Barista Twist Slim", mg: 6.0 },

  // --- THUNDER (expanded) ---
  { b: "THUNDER", n: "Thunder Apple Mint Slim", mg: 12.0 },
  { b: "THUNDER", n: "Thunder Citrus Slim", mg: 12.0 },
  { b: "THUNDER", n: "Thunder Cool Mint Slim", mg: 11.0 },
  { b: "THUNDER", n: "Thunder Black Max", mg: 15.5 },

  // --- FRE (expanded) ---
  { b: "FRE", n: "FRE Wintergreen 3mg", mg: 3.0 },
  { b: "FRE", n: "FRE Wintergreen 6mg", mg: 6.0 },
  { b: "FRE", n: "FRE Wintergreen 9mg", mg: 9.0 },
  { b: "FRE", n: "FRE Wintergreen 12mg", mg: 12.0 },
  { b: "FRE", n: "FRE Lush Tropical 6mg", mg: 6.0 },
  { b: "FRE", n: "FRE Lush Tropical 12mg", mg: 12.0 },
  { b: "FRE", n: "FRE Sweet 6mg", mg: 6.0 },
  { b: "FRE", n: "FRE Sweet 12mg", mg: 12.0 },
  { b: "FRE", n: "FRE Original 6mg", mg: 6.0 },
  { b: "FRE", n: "FRE Original 12mg", mg: 12.0 },

  // --- SKRUF (expanded) ---
  { b: "SKRUF", n: "Skruf Super White Slim Fresh Mint Medium 8.5mg", mg: 8.5 },
  { b: "SKRUF", n: "Skruf Super White Slim Indigo Berry", mg: 11.0 },
  { b: "SKRUF", n: "Skruf Super White Slim Purple Cassis", mg: 11.0 },
  { b: "SKRUF", n: "Skruf Super White Slim Nordic Liquorice", mg: 11.0 },
  { b: "SKRUF", n: "Skruf Super White Slim Aloe Fresh", mg: 10.0 },
  { b: "SKRUF", n: "Skruf Super White Slim Frozen Berry", mg: 11.0 },

  // --- FUMI (expanded) ---
  { b: "FUMI", n: "Fumi Blackcurrant Regular", mg: 8.0 },
  { b: "FUMI", n: "Fumi Watermelon Mint Regular", mg: 8.0 },
  { b: "FUMI", n: "Fumi Blackcurrant Strong", mg: 12.0 }
];

export const USER_BENCHMARKS = [
  { max: 3, label_en: "Top 10% (Casual)", label_cs: "Top 10% (Rekreační)", percentile: 90, msg_en: "You're elite! Minimal dependence.", msg_cs: "Jsi elita! Minimální závislost." },
  { max: 8, label_en: "Average", label_cs: "Průměr (Average)", percentile: 50, msg_en: "You are in the average range. Watch for increases.", msg_cs: "Jsi v průměru. Pozor na zvyšování." },
  { max: 15, label_en: "Heavy", label_cs: "Nadprůměr (Heavy)", percentile: 20, msg_en: "High use. Consider reducing.", msg_cs: "Vysoká spotřeba. Zvaž omezení." },
  { max: 999, label_en: "Ultra", label_cs: "Extrém (Ultra)", percentile: 5, msg_en: "Critical zone. A quit plan is recommended.", msg_cs: "Kritická zóna. Doporučujeme plán odvykání." }
];
